// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutonShootGatherAllShoot.h"
#include "DeployGather.h"
#include "DeployShooter.h"
#include "ShootTimed.h"
#include "RunGather.h"
#include "StopGather.h"
#include "RetractShooter.h"
#include "DriveForward.h"
#include "DoNothing.h"

AutonShootGatherAllShoot::AutonShootGatherAllShoot() {
	AddParallel(new DeployGather());
	AddParallel(new DeployShooter());
	AddSequential(new DoNothing());
	AddSequential(new DriveForward(12.0, 0.25));
	AddSequential(new ShootTimed());
	AddParallel (new RunGather());
	AddSequential(new DriveForward(136.0, 0.5));
	AddSequential(new DriveForward(-136.0, 0.5));
	AddParallel (new StopGather());
	AddSequential(new ShootTimed());
}
