// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutonShootOnly.h"
#include "DeployGather.h"
#include "DeployShooter.h"
#include "DoNothing.h"
#include "AutonShoot.h"
#include "DriveForward.h"

AutonShootOnly::AutonShootOnly() {
	//AddParallel(new DeployGather());
	AddSequential(new DeployShooter());
	AddSequential(new DoNothing());
	//AddSequential(new DriveForward(12.0, 0.25));
	AddSequential(new AutonShoot());
}
