#include "BackgroundShoot.h"
BackgroundShoot::BackgroundShoot() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void BackgroundShoot::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void BackgroundShoot::Execute() {
	Robot::shooter->StopShooting();
}
// Make this return true when this Command no longer needs to run execute()
bool BackgroundShoot::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void BackgroundShoot::End() {
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void BackgroundShoot::Interrupted() {
	End();
}
