#include "BackgroundGather.h"
BackgroundGather::BackgroundGather() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::gatherer);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void BackgroundGather::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void BackgroundGather::Execute() {
}
// Make this return true when this Command no longer needs to run execute()
bool BackgroundGather::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void BackgroundGather::End() {
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void BackgroundGather::Interrupted() {
	End();
}
