#include "BackgroundShoot.h"
BackgroundShoot::BackgroundShoot() {
	spinning = false;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void BackgroundShoot::Initialize() {
	spinning = false;
}
// Called repeatedly when this Command is scheduled to run
void BackgroundShoot::Execute() {
	if (Robot::shooter->IsDeployed()) {
		if (spinning) {
			Robot::shooter->ContinueSpinning();
		}
		else {
			Robot::shooter->StartSpinning();
			spinning = true;
		}
	}
	else {
		Robot::shooter->StopShooting();
		spinning = false;
	}
}
// Make this return true when this Command no longer needs to run execute()
bool BackgroundShoot::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void BackgroundShoot::End() {
	spinning = false;
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void BackgroundShoot::Interrupted() {
	End();
}
