#include "BackgroundGather.h"
#include <math.h>
BackgroundGather::BackgroundGather() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::gatherer);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void BackgroundGather::Initialize() {
}
void BackgroundGather::Execute() {
	Joystick *stick = Robot::oi->getDriveStick();
	if(fabs(stick->GetRawAxis(Joystick::kThrottleAxis))>0.5) {
		double speed = SmartDashboard::GetNumber("GatherSpeed");
		Robot::gatherer->motor->Set(speed);
	}
}
bool BackgroundGather::IsFinished() {
	return false;
}
void BackgroundGather::End() {
	Robot::gatherer->motor->Set(0.0);
}
void BackgroundGather::Interrupted() {
	End();
}
