#include "Climb.h"
Climb::Climb() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void Climb::Initialize() {
	Robot::climber->engageCount += 1;
}
void Climb::Execute() {
	if (Robot::climber->engageCount >= 2) {
		Robot::climber->engageClaw->Set(DoubleSolenoid::kReverse);
	}
}
bool Climb::IsFinished() {
	return false;
}
void Climb::End() {
	Robot::climber->engageCount -= 1;
}
void Climb::Interrupted() {
	End();
}
