#include "Climb.h"
Climb::Climb() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Climb::Initialize() {
	//Robot::climber->engageClaw->Set(DoubleSolenoid::kReverse);
	Robot::gatherer->deploy->Set(DoubleSolenoid::kReverse);
}
// Called repeatedly when this Command is scheduled to run
void Climb::Execute() {
}
// Make this return true when this Command no longer needs to run execute()
bool Climb::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void Climb::End() {
	//Robot::climber->engageClaw->Set(DoubleSolenoid::kForward);
	Robot::gatherer->deploy->Set(DoubleSolenoid::kForward);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Climb::Interrupted() {
	End();
}
