#include "DecreaseShooterRPM.h"
DecreaseShooterRPM::DecreaseShooterRPM() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void DecreaseShooterRPM::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void DecreaseShooterRPM::Execute() {
	double speed = SmartDashboard::GetNumber("ShooterSpeed");
	SmartDashboard::PutNumber("ShooterSpeed", speed - 5.0);
}
// Make this return true when this Command no longer needs to run execute()
bool DecreaseShooterRPM::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void DecreaseShooterRPM::End() {
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DecreaseShooterRPM::Interrupted() {
}
