#include "DoNothing.h"
DoNothing::DoNothing(double time) {
	defaultDelay = time;	//negative times are treated as 0.0 by SetTimeOut
	actualDelay = 0.0;
	timeToGo = 0.0;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void DoNothing::Initialize() {
	//if default delay is not specified then get delay from smart dashboard
	actualDelay = (defaultDelay > 0.0) ? defaultDelay : SmartDashboard::GetNumber("AutonDelay");
	timeToGo = (actualDelay > 0.0) ? Timer::GetPPCTimestamp() + actualDelay : 0.0;
}
void DoNothing::Execute() {
}
bool DoNothing::IsFinished() {
	return Timer::GetPPCTimestamp() >= timeToGo;
}
void DoNothing::End() {
}
void DoNothing::Interrupted() {
}
