#include "DoNothing.h"
DoNothing::DoNothing(double time) {
	defaultDelay = time;	//negative times are treated as 0.0 by SetTimeOut
	actualDelay = 0.0;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void DoNothing::Initialize() {
	//if default delay is not specified then get delay from smart dashboard
	actualDelay = (defaultDelay > 0.0) ? defaultDelay : SmartDashboard::GetNumber("Delay");
	if (actualDelay > 0.0) {
		SetTimeout(actualDelay);
	}
	//I am unshure what SetTimeout does if a negative time is given
}
void DoNothing::Execute() {
}
bool DoNothing::IsFinished() {
	return actualDelay <= 0.0 || IsTimedOut();
}
void DoNothing::End() {
	
}
void DoNothing::Interrupted() {
}
