#include "DriveForward.h"
DriveForward::DriveForward() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void DriveForward::Initialize() {
	double timeout = SmartDashboard::GetNumber("Fwd Duration");
	if (timeout < 0.0) timeout = 0.0;
	if (timeout > 2.0) timeout = 2.0;
	SetTimeout(timeout);
}
void DriveForward::Execute() {
	double speed = SmartDashboard::GetNumber("Fwd Speed");
	int mode = (int)Robot::oi->fwdChooser->GetSelected();
	if (speed > 0.5) speed = 0.5;
	if (mode == 1) {
		Robot::drivetrain->drive->TankDrive(0.90 * speed, speed, false);
	}
	else if (mode == 2) {
		Robot::drivetrain->drive->ArcadeDrive(speed, 0.0, false);
	}
	else {
		Robot::drivetrain->drive->Drive(speed, 0.0);
	}
}
bool DriveForward::IsFinished() {
	return IsTimedOut();
}
void DriveForward::End() {
	Robot::drivetrain->drive->Drive(0.0, 0.0);
}
void DriveForward::Interrupted() {
	End();
}
