// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef DRIVEFORWARD_H
#define DRIVEFORWARD_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveForward: public Command {
public:
	/*const double m_MAX_MAX_SPEED = 10;	//FIXME should
	const double m_MIN_MAX_SPEED = 6;*/
	double m_distance;
	double m_KeepGoingUntilTime;
	DriveForward(double distance = 0.0); //negative means drive backwards
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
