#include "IncreaseShooterRPM.h"
IncreaseShooterRPM::IncreaseShooterRPM() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void IncreaseShooterRPM::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void IncreaseShooterRPM::Execute() {
	double speed = SmartDashboard::GetNumber("ShooterSpeed");
	SmartDashboard::PutNumber("ShooterSpeed", speed + 25.0);
}
// Make this return true when this Command no longer needs to run execute()
bool IncreaseShooterRPM::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void IncreaseShooterRPM::End() {
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IncreaseShooterRPM::Interrupted() {
}
