// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ResetDrivetrainMotors.h"
ResetDrivetrainMotors::ResetDrivetrainMotors() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ResetDrivetrainMotors::Initialize() {
	Robot::drivetrain->leftMotorA->ChangeControlMode(CANJaguar::kVoltage);
	Robot::drivetrain->leftMotorA->EnableControl();
	Robot::drivetrain->leftMotorB->ChangeControlMode(CANJaguar::kVoltage);
	Robot::drivetrain->leftMotorB->EnableControl();
	Robot::drivetrain->rightMotorA->ChangeControlMode(CANJaguar::kVoltage);
	Robot::drivetrain->rightMotorA->EnableControl();
	Robot::drivetrain->rightMotorB->ChangeControlMode(CANJaguar::kVoltage);
	Robot::drivetrain->rightMotorB->EnableControl();
	Robot::drivetrain->drive->SetMaxOutput(12.0);
}
// Called repeatedly when this Command is scheduled to run
void ResetDrivetrainMotors::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool ResetDrivetrainMotors::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void ResetDrivetrainMotors::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ResetDrivetrainMotors::Interrupted() {
}
