#include "RunFeeder.h"
RunFeeder::RunFeeder() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void RunFeeder::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void RunFeeder::Execute() {
	Robot::shooter->mainMotor->Set(0);
	double speed = SmartDashboard::GetNumber("FeederSpeed");
	Robot::shooter->feedMotor->Set(-speed);
	Robot::shooter->flipper->Set(Relay::kReverse);
}
// Make this return true when this Command no longer needs to run execute()
bool RunFeeder::IsFinished() {
	// This command is connected to a WhileHeld button. When the button
	// is released, the command is cancelled and the default subsystem
	// command activates.
	return false;
}
// Called once after isFinished returns true
void RunFeeder::End() {
	Robot::shooter->StopShooting();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RunFeeder::Interrupted() {
	End();
}
