#include "RunGather.h"
RunGather::RunGather() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::gatherer);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void RunGather::Initialize() {
}
void RunGather::Execute() {
	double speed = SmartDashboard::GetNumber("GatherSpeed");
	Robot::gatherer->motor->Set(speed);
}
bool RunGather::IsFinished() {
	return false;
}
void RunGather::End() {
	Robot::gatherer->motor->Set(0.0);
}
void RunGather::Interrupted() {
	End();
}
