#include "SetShooterPreset1.h"
SetShooterPreset1::SetShooterPreset1() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void SetShooterPreset1::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void SetShooterPreset1::Execute() {
	SmartDashboard::PutNumber("ShooterSpeed", 2250.0);
}
// Make this return true when this Command no longer needs to run execute()
bool SetShooterPreset1::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void SetShooterPreset1::End() {
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetShooterPreset1::Interrupted() {
}
