#include "ShiftToLow.h"
ShiftToLow::ShiftToLow() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ShiftToLow::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void ShiftToLow::Execute() {
	Robot::drivetrain->ShiftIntoLowGear();
}
// Make this return true when this Command no longer needs to run execute()
bool ShiftToLow::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void ShiftToLow::End() {
	Robot::drivetrain->ShiftIntoHighGear();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShiftToLow::Interrupted() {
	End();
}
