#include "Shoot.h"
Shoot::Shoot() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Shoot::Initialize() {
	Robot::shooter->StartSpinning();
}
// Called repeatedly when this Command is scheduled to run
void Shoot::Execute() {
	Robot::shooter->ContinueShooting();
}
// Make this return true when this Command no longer needs to run execute()
bool Shoot::IsFinished() {
	// This command is connected to a WhileHeld button. When the button
	// is released, the command is cancelled and the default subsystem
	// command activates.
	return false;
}
// Called once after isFinished returns true
void Shoot::End() {
	Robot::shooter->StopShooting();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Shoot::Interrupted() {
	End();
}
