#include "StopGather.h"
StopGather::StopGather() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::gatherer);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
void StopGather::Initialize() {
}
void StopGather::Execute() {
	Robot::gatherer->motor->Set(0);
}
bool StopGather::IsFinished() {
	return true;
}
void StopGather::End() {
}
void StopGather::Interrupted() {
}
