
#include "TelOpDrive.h"
TelOpDrive::TelOpDrive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void TelOpDrive::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void TelOpDrive::Execute() {
	Joystick *stick = Robot::oi->getDriveStick();
	SmartDashboard::PutNumber("Stick Twist", stick->GetRawAxis(Joystick::kDefaultTwistAxis));
	SmartDashboard::PutNumber("Stick Y", stick->GetRawAxis(Joystick::kDefaultYAxis));
	Robot::drivetrain->drive->ArcadeDrive(stick, Joystick::kDefaultYAxis,
			                              stick, Joystick::kDefaultTwistAxis);
	if (Robot::drivetrain->leftMotorA->GetControlMode() != CANJaguar::kVoltage) {
			Robot::drivetrain->leftMotorA->ChangeControlMode(CANJaguar::kVoltage);
			Robot::drivetrain->leftMotorA->EnableControl();
	}
	if (Robot::drivetrain->leftMotorB->GetControlMode() != CANJaguar::kVoltage) {
			Robot::drivetrain->leftMotorB->ChangeControlMode(CANJaguar::kVoltage);
			Robot::drivetrain->leftMotorB->EnableControl();
	}
	if (Robot::drivetrain->rightMotorA->GetControlMode() != CANJaguar::kVoltage) {
			Robot::drivetrain->rightMotorA->ChangeControlMode(CANJaguar::kVoltage);
			Robot::drivetrain->rightMotorA->EnableControl();
	}
	if (Robot::drivetrain->rightMotorB->GetControlMode() != CANJaguar::kVoltage) {
			Robot::drivetrain->rightMotorB->ChangeControlMode(CANJaguar::kVoltage);
			Robot::drivetrain->rightMotorB->EnableControl();
	}
}
// Make this return true when this Command no longer needs to run execute()
bool TelOpDrive::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void TelOpDrive::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TelOpDrive::Interrupted() {
}
