// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Drivetrain: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
#define NUM_SPEED_SAMPLES 4
	double speedHistory[NUM_SPEED_SAMPLES];
	int nextSampleNum;
#define BASELINE_SHIFT_POINT 60.0
	double shiftPoint;
	bool automaticShiftingEnabled;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANJaguar* leftMotorA;
	CANJaguar* leftMotorB;
	CANJaguar* rightMotorA;
	CANJaguar* rightMotorB;
	RobotDrive* drive;
	DoubleSolenoid* shiftGear;
	Encoder* leftEncoder;
	Encoder* rightEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Drivetrain();
	void InitDefaultCommand();
	void ShiftIntoLowGear();
	void ShiftIntoHighGear();
	void ToggleShiftGears();
	void TakeSpeedSample();
	void ShiftAutomatically();
	void EnableAutomaticShifting(bool enabled);
	void Snapshot();
	void MotorSnapshot(CANJaguar *motor);
};
#endif
