#ifndef SHOOTER_H
#define SHOOTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
class Shooter: public Subsystem {
public:
	double shooterSpeed;
	double targetShooterSpeed;
	bool checkSpeedUntilReady;
	bool shooterReady;
	double timeToSwitchModes;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANJaguar* mainMotor;
	CANJaguar* feedMotor;
	Relay* flipper;
	AnalogChannel* frisbeeDirection;
	DoubleSolenoid* deploy;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Shooter();
	void InitDefaultCommand();
	void TakeSpeedSample();
	bool IsDeployed();
	void DeployShooter();
	void RetractShooter();
	void ToggleDeploy();
	void StartSpinning();
	void ContinueSpinning();
	void ContinueShooting();
	void StopShooting();
	void Snapshot();
	void MotorSnapshot(CANJaguar *motor);
private:
    void beginSpeedMode();
};
#endif
