#include "Support.h"
#include "../Robotmap.h"
Support::Support() : Subsystem("Support") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	perfTimer = RobotMap::supportPerfTimer;
	diagTimer = RobotMap::supportDiagTimer;
	accel = RobotMap::supportAccel;
	gyro = RobotMap::supportGyro;
	compressor = RobotMap::supportCompressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
void Support::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
